### ISSUE TITLE
Giant images in "tea of the month"

### ISSUE THREAD

**Issue by melissamcewen** [Reynaldoabv/Tea-Cozy#2]
I noticed these and this is a common issue. I'd recommend sizing the images by targeting the `img` element directly by changing this 

to

```css
.section-image img {
	height: 200px;
	width: 300px;
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
}

```

OR applying that class directly to the image
```html
<img src="resources/images/img-myrtle-ave.jpg" alt="forth-img" class="section-image">
```

There are also some strategies that involve making such images do not exceed their container that are described here:
https://stackoverflow.com/questions/25630915/image-expanding-larger-than-parent-div

But the thing to remember is if you have a large image and the div is set to be smaller, the image will not shrink to fit unless you apply some css properties to the image
